import { Cidade } from './types';

export const cidadesIniciais: Cidade[] = [
  { nome: "São Paulo", x: 74, y: 61 },
  { nome: "Rio de Janeiro", x: 86, y: 54 },
  { nome: "Belo Horizonte", x: 82, y: 64 },
  { nome: "Brasília", x: 54, y: 79 },
  { nome: "Salvador", x: 90, y: 87 },
  { nome: "Fortaleza", x: 98, y: 97 },
  { nome: "Recife", x: 95, y: 91 },
  { nome: "Curitiba", x: 65, y: 49 },
  { nome: "Porto Alegre", x: 52, y: 33 },
  { nome: "Florianópolis", x: 59, y: 41 },
  { nome: "Manaus", x: 15, y: 95 },
  { nome: "Belém", x: 35, y: 92 },
  { nome: "Goiânia", x: 56, y: 72 },
  { nome: "Campo Grande", x: 43, y: 62 },
  { nome: "Cuiabá", x: 39, y: 71 },
  { nome: "Teresina", x: 87, y: 93 },
  { nome: "Natal", x: 98, y: 89 },
  { nome: "João Pessoa", x: 96, y: 88 },
  { nome: "Maceió", x: 94, y: 85 },
  { nome: "Aracaju", x: 92, y: 82 },
  { nome: "Palmas", x: 45, y: 79 },
  { nome: "Macapá", x: 22, y: 99 },
  { nome: "Rio Branco", x: 10, y: 81 },
  { nome: "Boa Vista", x: 9, y: 97 },
  { nome: "Porto Velho", x: 20, y: 85 },
  { nome: "São Luís", x: 83, y: 95 },
  { nome: "Vitória", x: 84, y: 68 },
  { nome: "Uberlândia", x: 64, y: 68 },
  { nome: "Campinas", x: 73, y: 59 },
  { nome: "Londrina", x: 62, y: 52 }
];
